version: '3.8'
services:
  app:
    image: magna-fe
    build:
      context: ./
      target: dev
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
  volumes:
        - .:/app
        - /app/node_modules
        - /app/.next
