name: Deploy to VPS

on:
  push:
     branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build and start services
      run: |
        # Check if docker-compose is already running
        if [ "$(docker ps -q)" ]; then
          echo "Stopping existing containers"
          docker compose down
        else
          echo "No running containers found"
        fi
        
        docker-compose build
        docker-compose up -d
    
