name: Deploy to VPS

on:
  push:
     branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build and start services
      run: |
        if [ "$(sudo docker ps -q)" ]; then
          echo "Stopping existing containers"
          sudo docker compose down
        else
          echo "No running containers found"
        fi
        
        sudo docker-compose build
        sudo docker-compose up -d
    
