# .github/workflows/deploy.yml
name: Deploy to VPS

on:
  workflow_run:
    workflows:
      - Build Next.js Application
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Download build artifact
      uses: actions/download-artifact@v3
      with:
        name: nextjs-build

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.VPS_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        echo "${{ secrets.VPS_HOST }}" > ~/.ssh/known_hosts

    - name: Deploy to VPS
      run: |
        scp -r .next user@${{ secrets.VPS_IP }}:/var/php/nextjs-app
        ssh ${{ secrets.USER }}@${{ secrets.VPS_IP }} "cd /var/php/nextjs-app && pm2 restart ecosystem.config.js"
