name: CI/CD for Next.js

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Next.js to VPS
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    # Step 3: Install dependencies
    - name: Install dependencies
      run: npm install

    # Step 4: Build Next.js project
    - name: Build Next.js project
      run: npm run build

    # Step 5: Copy files to VPS
    - name: Deploy to VPS
      env:
        HOST: ${{ secrets.VPS_HOST }}
        USER: ${{ secrets.VPS_USER }}
        PRIVATE_KEY: ${{ secrets.VPS_PRIVATE_KEY }}
      run: |
        echo "$PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem
        scp -o StrictHostKeyChecking=no -i private_key.pem -r .next static public package.json package-lock.json ${USER}@${HOST}:/var/php/nextjs
        ssh -o StrictHostKeyChecking=no -i private_key.pem ${USER}@${HOST} << 'EOF'
        cd /var/php/nextjs
        sudo npm install --production
        sudo pm2 delete all || true
        sudo pm2 start npm --name "nextjs-app" -- start
        EOF
        sudo rm private_key.pem
